// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvg-SFs3KbZVU8FZhwLZZzZNHeUK_PQo',
    appId: '1:60208840695:android:2db53cca1ca749287f78f2',
    messagingSenderId: '60208840695',
    projectId: 'quick-dash-84f6a',
    databaseURL: 'https://quick-dash-84f6a-default-rtdb.firebaseio.com',
    storageBucket: 'quick-dash-84f6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlqLQTjzVdfQAXoiHXSGc-XwLk4BwX5LA',
    appId: '1:60208840695:ios:c898a22bcf4f5fed7f78f2',
    messagingSenderId: '60208840695',
    projectId: 'quick-dash-84f6a',
    databaseURL: 'https://quick-dash-84f6a-default-rtdb.firebaseio.com',
    storageBucket: 'quick-dash-84f6a.firebasestorage.app',
    androidClientId: '60208840695-1d7tefbqt46vti585bi4pmicrvs0u0g0.apps.googleusercontent.com',
    iosClientId: '60208840695-v9nctp1ie5i6fdolg89n25kfh3d4nsec.apps.googleusercontent.com',
    iosBundleId: 'com.quickdash.customer',
  );
}
